### ISSUE TITLE
How to convert yolov3 model trained in caffe with self defined layer

### ISSUE THREAD

**Issue by jinfagang** [XiaoMi/mace-models#10]
How to convert own trained yolov3 model into mace ? Is there any convert tutorial?

**Comment by llhe** [comment]
For model conversion, check the documents: https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html

For yolo, you may need customized Ops: https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html

**Comment by gaopeipeiok** [comment]
Did you complete yolo3 model on android。I have got the output datas，But I did not decode the datas，I am learning the yolo_layer.c. Maybe we could exchange experience .
