### ISSUE TITLE
DeepLab Test

### ISSUE THREAD

**Issue by ilous12** [XiaoMi/mace-models#11]
Hi. nice work

I will try to run my own deeplabv3plus model on mace framework. So I want to know what was model changes for mace.

I saw your description about deeplabv3plus model
> - input_tensors: sub_7
> -output_tensors: ResizeBilinear_2
> -input_shapes: 1,513,513,3
> -output_shapes: 1,65,65,21

I understood original deeplab v3 plus was below.
> - input_tensors: ImageTensor
> -output_tensors: SementicPredictions
> -input_shapes: 1,513,513,3
> -output_shapes: 1,513,513,21

What do you fix for mace framework? Can you tell me about that? or your training code.

if you use "transform_graph", please share me command.

**Comment by llhe** [comment]
@ilous12 Here is the description: https://github.com/XiaoMi/mace-models/tree/master/deeplab-v3-plus

Part of the model (sub_7 ~ ResizeBilinear_2) is converted for MACE.

**Comment by ilous12** [comment]
Thanks for reply.
Deeplab had 21 label and  I tried to run your model. But I got invalid result. Is It working valid?
I only saw background label.

**Comment by hoonkai** [comment]
@llhe Do you know why the output shapes are 1,65,65,21 rather than 1,513,513,21?

**Comment by lydoc** [comment]
@hoonkai  We use "ResizeBilinear_2" node which has such a shape (1,65,65,21) as output.

**Comment by hoonkai** [comment]
@lydoc But if the output layer is 65x65x21, how should the 512x512 mask bitmap be built? Or is the result meant to be a 64x64 mask bitmap?

**Comment by lydoc** [comment]
@lydoc You can resize the output size to 512 * 512.
