### ISSUE TITLE
deploy Yolov3 with mace

### ISSUE THREAD

**Issue by XinCode** [XiaoMi/mace-models#14]
Hi mace team, I have a yolov3 model trained with own dataset (9 classes). I understand I need to first convert the yolo model to tf format, and then convert the tf model to mace model format. My questions are: 
(1) Do you prefer any darknet -> tf conversion tool? I tried multiple tools but different tools generate significantly different pb model structure. Kindly suggest the [official] tools you are using to convert darknet yolo model to tf model format.
(2) To deploy yolov3 with mace, besides yml file, is there any other staff I need to configure? Could you provide a simple case/demo where yolov3 is deployed?

**Comment by lu229** [comment]
@XinCode Sorry, we haven't supported the model conversion tool for darknet. For the supported modles. there is no others to configure apart from the yml file.

**Comment by XinCode** [comment]
@lu229 thanks for your quick reply, I have converted yolov3 model to mace format. Next will be the detection test on android. I just realize that most android tutorials are about image classification using mobilenet, could you point where I can refer to an object detection example?

**Comment by lu229** [comment]
@XinCode You can reference the example in MACE, the project'path: mace/examples/android

**Comment by gaopeipeiok** [comment]
Did you complete yolo3 model on android。I have got the output datas，But I did not decode the datas，I am learning the yolo_layer.c. Maybe we could exchange experience .
