### ISSUE TITLE
Support object detection models

### ISSUE THREAD

**Issue by XinCode** [XiaoMi/mace-models#16]
Hi mace team, about object detection models:
(1) ssd-mobilenetv1 only support caffe model, do you currently support tensorflow model?
(2) Do you support other more advanced object detection models, like ssd with more complicated backbone, e.g., resnet50, or even faster rcnn models?

**Comment by lydoc** [comment]
Hi,
(1) Yes, we do support the tensorflow model, you can use ClassPredictor and BoxEncodingPredictor as output nodes.
(2) For faster rcnn models, there may be some ops we do not support now, but you can create a custom op if it is not supported yet. https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html

**Comment by XinCode** [comment]
@lydoc noted with thanks.
