### ISSUE TITLE
how to set input data, after kaldi convert to onnx model, 

### ISSUE THREAD

**Issue by jon-soc** [XiaoMi/mace-models#17]
i would to create input data and validation data for cvte onnx model , can you give some suggestion about this ?

thanks

**Comment by eudora-jia** [comment]
![image](https://user-images.githubusercontent.com/30928373/63947716-080f9200-caaa-11e9-95fc-ba1f46b4052f.png)
if your model input id is number,you should set like this :

![image](https://user-images.githubusercontent.com/30928373/63947903-5d4ba380-caaa-11e9-99e7-879a54274fd1.png)
