### ISSUE TITLE
yolo v3的fps

### ISSUE THREAD

**Issue by jiguanglu** [XiaoMi/mace-models#19]
1: 首先感谢 mace团队，研发出这么好的框架。
2: 请问各位大佬，model-zoo里的yolo-v3模型，诸位在android下测试过吗？如果测试过，fps大概 
     是多少？我自己想要在高通845的板子上转化一版yolo-v3，想问下在mace框架下的fps。
3: 我看mace支持的op好像没有LeakyRelu，请问贵团队能否提供自定义的LeakyRelu？

希望大佬赐教啊。

**Comment by lydoc** [comment]
如电话沟通，model zoo里应该是yolo v3 large，845 cpu大概在1s-2s，gpu应该在几百毫秒，具体需要再测一下。目前应该支持leakyRelu。
