### ISSUE TITLE
Unable to connect the url..

### ISSUE THREAD

**Issue by mariolew** [XiaoMi/mace-models#2]
Hi, I can't connect the url in the yaml file, so how can I obtain those models?

**Comment by llhe** [comment]
Which URL?

**Comment by mariolew** [comment]
http://cnbj1-inner-fds.api.xiaomi.net/mace/mace-models/squeezenet/SqueezeNet_v1.1/model.prototxt

**Comment by llhe** [comment]
@mariolew 
Thanks for the report, this is a internal link. We will change this bad link.

**Comment by llhe** [comment]
@mariolew Fixed.

**Comment by Zibri** [comment]
also cnbj1-fds.api.xiaomi.net is not reachable.
