### ISSUE TITLE
How to make model: caffe ssd-mobilenet-v1 support hexagon dsp .

### ISSUE THREAD

**Issue by mccoychang** [XiaoMi/mace-models#20]
Could you provide examples or suggestion  in caffe ssd-mobilenet-v1 to support hexagon dsp?
Please help,Thanks.

**Comment by lee-bin** [comment]
For quantization and hexagon, you can refer to [Quantization](https://mace.readthedocs.io/en/latest/user_guide/quantization_usage.html) in MACE docs.
