### ISSUE TITLE
Please provide training scripts (or at least more details) for realtime-style-transfer model.

### ISSUE THREAD

**Issue by ljoukov** [XiaoMi/mace-models#22]
README for https://github.com/XiaoMi/mace-models/tree/master/realtime-style-transfer says that: "This realtime style transfer model was compressed and optimized from here (fast style transfer project)."

Could you please provide more details what exactly was done and share training script source code? Thanks!

**Comment by TonyMou** [comment]
We used a step-traning method to train this model, and the step-training codes are here(https://github.com/TonyMou/fast-style-transfer/tree/support-step-training).
