### ISSUE TITLE
run on PC

### ISSUE THREAD

**Issue by CheungBH** [XiaoMi/mace-models#23]
Hello. I wonder whether the converted models can be run on the PC. If so, are there any examples for deployment?

**Comment by lu229** [comment]
@CheungBH Mace can run on PC with no optimization，you can reference [Advanced usage for Bazel users](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#advanced-usage-for-bazel-users) and set the target_abis to `[host]` in the yml file.

**Comment by CheungBH** [comment]
Well, I see. By the way, after converting the model with setting the target_abis to [host], how can I deploy it on PC? Are there any simple demos like image classification or object detection on PC with a converted mace model?

**Comment by lu229** [comment]
@CheungBH , Sorry, there is no demos for PC, MACE is developed for mobile devices.

**Comment by CheungBH** [comment]
Thank you. BTW, are there any official demos apart from image classification? like object detection and pose estimation, etc.

**Comment by lu229** [comment]
@CheungBH No, but perhaps you can reference the [mace-kit](https://github.com/XiaoMi/mace-kit) project
