### ISSUE TITLE
fast-style-transfer模型的计算用时

### ISSUE THREAD

**Issue by czczup** [XiaoMi/mace-models#25]
请问fast-style-transfer模型在GPU下处理一张480\*640\*3的图像大约需要多少时间？

我试过用tensorflow lite部署这个模型，用GPU跑一张480\*640\*3的风格迁移大概需要6s。因为tensorflow lite不支持在GPU上计算instance norm，所以非常耗时，mace存在这个问题吗？

**Comment by lu229** [comment]
@czczup 可以自行测试一下? 不同的硬件速度不相同, 另外在fast-style-transfer模型中没有找到Instance Norm, 你那边测试的和mace-models中的是同一个么?

**Comment by czczup** [comment]
> @czczup 可以自行测试一下? 不同的硬件速度不相同, 另外在fast-style-transfer模型中没有找到Instance Norm, 你那边测试的和mace-models中的是同一个么?

https://github.com/lengstrom/fast-style-transfer
我也是使用这个仓库训练的，是同一个模型
https://github.com/lengstrom/fast-style-transfer/blob/master/src/transform.py
在这个代码里有instance norm

**Comment by lu229** [comment]
@czczup 用[netron](https://lutzroeder.github.io/netron/)查看模型, 有这个op么?您看的模型文件的地址是?

**Comment by czczup** [comment]
> @czczup 用[netron](https://lutzroeder.github.io/netron/)查看模型, 有这个op么?您看的模型文件的地址是?

我看了一下另外一个文件夹：https://github.com/XiaoMi/mace-models/tree/master/realtime-style-transfer，这里面有性能测试。

**Comment by czczup** [comment]
我跑通了，小米优化真的牛！
用骁龙845测试，GPU模式
1000*1000用时1-2s，内存占用~0.8G，比tflite好了n个数量级。
