### ISSUE TITLE
build source code in Mac, build Error

### ISSUE THREAD

**Issue by chenjiaoAngel** [XiaoMi/mace-models#9]
ERROR: Config value android is not defined in any .rc file
where the value android defined
I use export ANDROID_NDK_HOME=/Users/chenjiao04/Documents/android-ndk-r15c
but it doesn't work

**Comment by lee-bin** [comment]
According to https://github.com/bazelbuild/bazel/issues/4502, tools/bazel.rc is no longer being read after bazel 0.17.1. So you may:
1. Downgrade bazel to work around.
2. Or move tools/bazel.rc to .bazelrc in MACE workspace to conform to new bazel.

We will solve it later.

**Comment by chenjiaoAngel** [comment]
OK，i will  try. Thank you very much
